mysql:
  image: postgresql
  ports:
    - "5432:5432"
  expose:
    - "5432"
  environment:
    - POSTGRES_USER=dhananjay@dhananjaydbtest
    - POSTGRES_PASSWORD=Dhanuki@1234
    - POSTGRES_DB=demo
    - POSTGRES_ROOT_PASSWORD=root
  volumes:
    - "./conf.d:/etc/postgres/conf.d:ro"